### ISSUE TITLE
kscan有的协议识别不出来

### ISSUE THREAD

**Issue by rechallage** [qi4L/KscanPro#3]
![image](https://github.com/qi4L/KscanPro/assets/85208463/33208e65-93ce-441d-b6d6-4ca06a472067)
对方开启了rmi协议kascan没有识别出协议类型
![image](https://github.com/qi4L/KscanPro/assets/85208463/9777ce1a-e72a-49d2-a4ad-9933da1635f0)

**Comment by qi4L** [comment]
闲着可以增加该协议

**Comment by qi4L** [comment]
![Image](https://github.com/user-attachments/assets/138398ee-a322-473d-b432-891e032730a3)
